### ISSUE TITLE
Device Authentication keys on newer fireTV devices 

### ISSUE THREAD

**Issue by trektronic** [gollo/hassio-addons#4]
New Amazon FireTV devices running KitKat or greater require keys. Starting the add-on will not let me connect to device. 

Log: 
> starting version 3.2.2
>Traceback (most recent call last):
>  File "/usr/bin/firetv-server", line 11, in <module>
>    load_entry_point('firetv==1.0.5', 'console_scripts', 'firetv-server')()
>  File "/usr/lib/python2.7/site-packages/firetv/__main__.py", line 242, in main
>    _add_devices_from_config(args)
>  File "/usr/lib/python2.7/site-packages/firetv/__main__.py", line 231, in _add_devices_from_config
>    add(device, config['devices'][device]['host'])
>  File "/usr/lib/python2.7/site-packages/firetv/__main__.py", line 88, in add
>    devices[device_id] = FireTV(str(host))
>  File "/usr/lib/python2.7/site-packages/firetv/__init__.py", line 98, in __init__
>    self.connect()
>  File "/usr/lib/python2.7/site-packages/firetv/__init__.py", line 108, in connect
>    serial=self.host)
>  File "/usr/lib/python2.7/site-packages/adb/adb_commands.py", line 76, in ConnectDevice
>    return cls.Connect(handle, **kwargs)
>  File "/usr/lib/python2.7/site-packages/adb/adb_commands.py", line 99, in Connect
>    device_state = cls.protocol_handler.Connect(usb, banner=banner, **kwargs)
>  File "/usr/lib/python2.7/site-packages/adb/adb_protocol.py", line 288, in Connect
>    'Device authentication required, no keys available.')
>adb.usb_exceptions.DeviceAuthError: Device authentication required, no keys available.

There is an issue open on the python-firetv github by happy leaves, but not sure how to fix this issue in hassio. 

https://github.com/happyleavesaoc/python-firetv/issues/49

**Comment by JeffLIrion** [comment]
Use this custom component: https://github.com/JeffLIrion/homeassistant_native_firetv

**Comment by mixpix405** [comment]
@JeffLIrion Excuse my ignorance, but, is it possible to install custom components using Hass.io?

**Comment by JeffLIrion** [comment]
Absolutely, just copy the `firetv.py` file to `/config/custom_components/media_player/firetv.py`.

**Comment by mixpix405** [comment]
Awesome - thanks! I'll give it a shot tomorrow.

**Comment by inverse** [comment]
@JeffLIrion thanks for your work! How does this kinda functionality get put into the core?

**Comment by JeffLIrion** [comment]
I could submit a PR to Home Assistant, but I don't know if it will get approved until the dependencies get released on pypi.
